### ISSUE TITLE
"memory"

### ISSUE THREAD

**Issue by Lohoris** [dumblob/mysql2sqlite#65]
Running the script I get the mysterious message "memory".

And that's it, just "memory", nothing else **at all**.

While the amount of rows per table is correct, and the PRIMARY and UNIQUE keys seem ok, the **FOREIGN keys are weird**, at least if I open them using SQLPro. They look like this:

```
  FOREIGN KEY (`fragged_player`) REFERENCES (null) () `pixp_user` (`user_id`,
  FOREIGN KEY (`fragger_player`) REFERENCES (null) () `pixp_user` (`user_id`,
```

When in an **old correct version** of the file they looked like this:

```
  FOREIGN KEY (fragger_player) REFERENCES pixp_user (user_id),
  FOREIGN KEY (fragged_player) REFERENCES pixp_user (user_id),
```

I don't have a working version of the application right now, so I can't test it yet; in case I'll keep you posted.

Feel free to ask me for clarifications or specific debugging.

PS: keep in mind this is a very **small** db, so there cannot be a real memory error. I mean, if there is, it's because there is some bad loop of some sorts, certainly not because of actual db size.

---

Versions:

```
mysqldump --version
mysqldump  Ver 10.17 Distrib 10.4.10-MariaDB, for osx10.14 (x86_64)

sqlite3 --version
3.24.0 2018-06-04 14:10:15 95fbac39baaab1c3a84fdfc82ccb7f42398b2e92f18a2a57bce1d4a713cbaapl
```

**Comment by dumblob** [comment]
Was your SQL code dumped from MySQL using the commands in readme? We don't (and can't) support any other syntax :cry:.

**Comment by Lohoris** [comment]
> Was your SQL code dumped from MySQL using the commands in readme? We don't (and can't) support any other syntax 😢.

It was.

I mean, I just added the user and the password, but that's about it.

`mysqldump --skip-extended-insert --compact [options]... DB_name > dump_mysql.sql`

became something like

`mysqldump --skip-extended-insert --compact -u pixp pixp -P > dump_mysql.sql`

(not sure I remember this exactly, but it was basically that, I only added username and pwd)

I have now tried to alter the tables manually using SQLPro, but trying to edit the FOREIGN keys crashes it, and trying to delete them gives a syntax error.

(of course you can't do support for SQLPro here, I'm telling this just so you know that the created db was problematic)

Keep in mind that being the db quite simple I could recreate it by hand (annoying but not a big deal), but I appreciate your effort in writing this tool so I'd like to help you anyway.

**Comment by Lohoris** [comment]
Ok this might or might not help you: I managed to convert the db using this other script https://github.com/techouse/mysql-to-sqlite3

However, I had a couple of adjustments to make. Namely, there were two INDEXes that the script didn't like: it told me they already existed.

Not really sure if it could be the same problem or a different one.

(I still have to actually test the db live, so far I've only converted it)

**Comment by dumblob** [comment]
Thanks for your effort. Unfortunately the python app https://github.com/techouse/mysql-to-sqlite3 can't be of any help here, because they are "cheating" :wink:. They use MySQL to load the DB (either to memory or to an on-disk temporary DB) and then use the MySQL API to read the data and information out and assemble SQLite syntax out of it. So it won't work for huge databases (or be very slow). We use a very fast (though error prone and unsafe) approach of on the fly rewriting (transpilation) using nearly no memory and no temporary storage and having no dependencies except for POSIX stuff.

Could you please provide the whole MySQL dump or at least the problematic parts (e.g. through pastebin) and then the resulting output you get from `mysql2sqlite` (please use the latest git version - we're actually not doing any releases yet).

**Comment by Lohoris** [comment]
_(sorry I've been quite busy these days, and wasn't able to do any test… I'll update you if I can!)_

**Comment by markstickley** [comment]
I have exactly the same problem. I initially got it and thought it was because I was running it on an EC2 instance but I downloaded the dump and I get the same on my MacBook. "memory".

It gives that error on the very first statement:

```
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `articles` (
  `articleID` int(11) NOT NULL AUTO_INCREMENT,
  `include` text NOT NULL,
  `title` text NOT NULL,
  `date` date NOT NULL DEFAULT '0000-00-00',
  PRIMARY KEY (`articleID`)
) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;
```

**Comment by dumblob** [comment]
@markstickley which AWK (and version) are you using? This is all weird - I've tested the latest version from git and with recent GNU AWK it works without any issues (as it did in Nov 2019 when this thread got opened).

**Comment by markstickley** [comment]
OK I'm not too familiar with awk but a bit of googling got me to this (on my MacBook):
```
$ awk -Wversion 2>/dev/null || awk --version
awk version 20070501
```

Bit different on my Ubuntu EC2 instance:
```
$ awk -Wversion 2>/dev/null || awk --version
GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)
Copyright (C) 1989, 1991-2015 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.
```

Hope that helps...

**Comment by dumblob** [comment]
Thanks - both versions are supported by this script. So let's summarize.

1) you ran `mysqldump ...` and got `file.sql` from it
2) you ran `./mysql2sqlite file.sql > file2.sql`
3) you ran `sqlite3 file2.db < file2.sql`
4) you noticed message `memory` and an error code on the command line (i.e. in `$?` variable there was no `0`)
5) you noticed there is no `file2.db` file

I've tried exactly this process, but it went like this:

1) I took the example code from https://github.com/dumblob/mysql2sqlite/issues/65#issuecomment-573162370 and put it in `file.sql`
2) I ran `./mysql2sqlite file.sql > file2.sql` (I got no errors, no complaints, no warnings, no issues)
3) I ran `sqlite3 file2.db < file2.sql` (be careful, `file2.db` must not exist as otherwise `sqlite3` will complain about existing tables as the `create table...` is without `if not exists`)
4) I noticed message `memory` (which is fine as that's what SQLite `PRAGMA journal_mode = MEMORY;` outputs) and no error code on the command line (i.e. in `$?` variable there was `0`)
5) I noticed there is `file2.db` file
6) I ran `sqlite3 file2.db` (which opened in an interactive mode)
7) I ran `select * from articles;` and it ran fine and returned empty result without any errors
8) I closed the db with `.exit`

Btw. you can also run `sqlite3` with the `-echo` argument to see each command and sqlite3's response line by line.

**Comment by markstickley** [comment]
OK this is really helpful thank you.

I actually ran the commands as instructed under the Usage section in the readme but I assume that and these instructions are basically doing the same thing.

I think I just assumed that the `memory` message was an error without any other context. Having completed the steps you outlined (and ignoring the memory output) it seem to have worked great. Thank you very much for your help!
