### ISSUE TITLE
Converting DECIMAL(X,Y) to Sqlite

### ISSUE THREAD

**Issue by crenelle** [dumblob/mysql2sqlite#70]
Is it possible to, when converting a dump file from mysql to a sqlite db, to convert the DECIMAL[X,Y) columns to TEXT with TEXT affinity?

I seem to be running into a problem where, when loading rows, the column data is being converted to double because the columns are TEXT with NUMERIC affinity. 

This is fine when doing searches, not so much when the columns are part of a computation where the precision is a factor, I think. 

Sqlite3 "doesn't support" DECIMAL per se. I'm in the process of looking at lots of source to see where conversion to double is occurring, I don't quite yet have a handle on this.

**Comment by dumblob** [comment]
Yeah, Sqlite affinity is just a suggestion which usually (but not always) designates default conversion **when querying** (affinity has nothing to do with storage which shall be fully type agnostic).

So I'm afraid we can't do anything about this in this conversion script, because the only place where you can reliably solve this is in your queries where you should use conversion functions.

**Comment by crenelle** [comment]
Okdoke!

Tnx!
