### ISSUE TITLE
Error: near line : too many terms in compound SELECT

### ISSUE THREAD

**Issue by AP365** [dumblob/mysql2sqlite#79]
Hello, i'm having this problem in a server with Red Hat Enterprise Linux Server release 7.5 (Maipo)

This is my execution line:
./mysql2sqlite/mysql2sqlite mydb.sql | sqlite3 mydb.sql.db

The errors are like this:
memory
Error: near line 78: too many terms in compound SELECT

sqlite3 --version:
3.7.17 2013-05-20 00:56:22

On my local computer (ubuntu 18.04) works fine. The only thing i can see different is 
sqlite3 --version
3.22.0 2018-01-22 18:45:57

Help?

**Comment by dumblob** [comment]
`mysql2sqlite` doesn't check for sqlite limits (they are also version-dependent so it doesn't even make sense to try). The error you're seeing is due to [sqlite having by default an artificial limit of 500 terms in one select statement](https://www.sqlite.org/limits.html ).

This limit is only changeable during sqlite recompilation :cry:.

I'd strongly recommend changing the select statements into smaller ones as we can't do this automatically in this script. Feel free to close this issue.

**Comment by AP365** [comment]
Solved upgrading sqlite3 on the server :)

**Comment by dumblob** [comment]
Glad you solved it!

Should you know AWK, feel free to review PRs in this repository - we need more eyes as there are pretty big changes lurking.
