### ISSUE TITLE
mysql2sqlite: command not found

### ISSUE THREAD

**Issue by junerockwell** [dumblob/mysql2sqlite#9]
I downloaded mysql2sqlite straight from Github. I'm not sure where to go from there. 

I'm using the Mac Terminal. I went to the Downloads folder where my `.sql` files are. I want to test and see if I can work this. So I typed in `mysql2sqlite myTable.sql | sqlite3 mySqlite.db` and I get the `mysql2sqlite: command not found`.

I know I'm not doing this correctly. Let me know what I need to do to be able to convert one or two MySQL tables into an Sqlite3 database.

**Comment by dumblob** [comment]
Thank you for pointing it out. There was a typo in the shebang in the script and also in README. Now it's fixed. Please fetch the current git version (newer or equal to 1b0b5d610c6090422625a2c58d2c23d2296eab3a) and run it like following.

~~~~
./mysql2sqlite myTable.sql | sqlite3 mySqlite.db
~~~~
(note the `./` at the beginning)

Please close this issue if this fixed it for you.

**Comment by fuzzy76** [comment]
You probably also need to ```chmod u+x ./mysql2sqlite``` first.

**Comment by mdinh186** [comment]
I followed this instruction and got into another erro: 

/usr/bin/awk: can't open file database.sql
 source line number 16
memory

**Comment by dumblob** [comment]
@mdinh186 which operating system are you using? Could you please copy the whole output (including how exactly are you executing the command etc.) and post it as a [code quote](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code ) here?

By the way for convenience we use the shebang `#!/usr/bin/awk -f` even though it's not POSIX (and thus not portable), but works on most major platforms. You can also run `awk -f /path/to/the/script/mysql2sqlite dump_mysql.sql`, which should be a portable way running it.

**Comment by mdinh186** [comment]
My Ox is macOS 10.12 Sierra. After my first comment, I figured maybe the reason was I didn't include path to the script, thus I changed the directory and run this line (mysql file is in the same folder with the script): 
```mysql2sqlite MDinh$ ./mysql2sqlite wwhypda.sql | sqlite3 test.db ```
Got line ```memory``` as mentioned. The command out put `test.db` but it's empty file. 

I followed your instruction and run: 

```mysql2sqlite MDinh$ awk -f /mysql2sqlite wwhypda.sql ```
and got: 
```
awk: can't open file /mysql2sqlite
 source line number 1 source file /mysql2sqlite
 context is
	 >>>  <<< 
```

**Comment by dumblob** [comment]
@mdinh186 thank you. Could you please again switch to the directory with the `mysql2sqlite` script and your `wwhypda.sql` file and run:

~~~~
./mysql2sqlite wwhypda.sql > sqlite00.sql
head sqlite00.sql
printf '\nXXXXXXXXXXXXXXXXXXXX\n\n'
tail sqlite00.sql
~~~~

Post the whole output of the commands above here in code quotes.

Should there be any private content (password hashes, security information, personal details, ...) in the output, please first change each such private content character to `X` before copying the text here.

**Comment by mdinh186** [comment]
Sure,
```$ ./mysql2sqlite wwhypda.sql > sqlite00.sql```
created an empty file 

```head sqlite00.sql```
> PRAGMA synchronous = OFF;
PRAGMA journal_mode = MEMORY;
BEGIN TRANSACTION;
END TRANSACTION;

`printf '\nXXXXXXXXXXXXXXXXXXXX\n\n'`

>XXXXXXXXXXXXXXXXXXXX

`tail sqlite00.sql`

>PRAGMA synchronous = OFF;
PRAGMA journal_mode = MEMORY;
BEGIN TRANSACTION;
END TRANSACTION;

**Comment by dumblob** [comment]
Thank you @mdinh186. This means nothing was converted (the message `memory` is from sqlite3). Could you please check that `wwhypda.sql` is not an empty file and that it contains at least some uncommented MySQL commands?

Also, could you please post `head -n 20 wwhypda.sql` and `tail -n 20 wwhypda.sql` (again with private info changed for `X` characters)?

**Comment by mdinh186** [comment]
My sincere apology, I never realized that I run the script on wrong copy while the file I want to convert is in the other table. Sorry about such hassle dealing with nonsense empty file. I run the script again, this time it converted  to 7 out of 30 tables. 
Again, I got line `memory` before all the errors were printing.
And there goes many lines. I included head 20 below to check corresponding line, line 10 doesn't contain any `CREATE` statement. 
>  Error: near line 10: near "CREATE": syntax error
....
Error: near line 352: near "ALGORITHM": syntax error
...
Error: near line 398: no such table: main.Image

Now  run `head -n 20` displayed: 

># ************************************************************
# Sequel Pro SQL dump
# Version 3408
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: XXXX (MySQL 5.5.16-log)
# Database: wwhypda
# Generation Time: 2012-10-05 10:22:14 +0200
# ************************************************************

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

And `tail -n 20`: 
>   `wwhypda`.`rock_type`.`rt_id` AS `rt_id`,count(`wwhypda`.`measure`.`msr_value`) AS `msr_number`
from ((`rock_type` left join `sample` on((`wwhypda`.`rock_type`.`rt_id` = `wwhypda`.`sample`.`key_rt`))) left join `measure` on((`wwhypda`.`measure`.`id_smpl` = `wwhypda`.`sample`.`id_Sample`)))
where (`wwhypda`.`rock_type`.`rt_status` = 1) group by `wwhypda`.`rock_type`.`rt_name`;

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

I looked at the sql script to check on lines that weren't successfully converted. It's either near syntax `KEY` or when data is inserted into the tables. 
Also, some tables that weren't converted have many NULL value.

**Comment by dumblob** [comment]
(I've adjusted your comment to use `~~~~` before and after each code sections to improve readability)

Oh, now it's completely clear. Sequel Pro has it's very own exporting code (see the method `- (void)exportOperation` in https://github.com/sequelpro/sequelpro/blob/master/Source/SPSQLExporter.m#L349 ) and does not use the `mysqldump` command provided by MySQL. Sequel Pro does not obey the same export syntax rules as MySQL and because `mysql2sqlite` depends on these specifics (as `mysql2sqlite` does not and will never contain a full-featured SQL parser), it can't work.

I can see several options:

1. Contact the [Sequel Pro](https://github.com/sequelpro/sequelpro ) project by raising an issue with a request to change the export syntax to the exact syntax `mysqldump` uses. Feel free to link to this issue, so that the contributors to *Sequel Pro* know what's going on and how to potentially test any changes to exporting syntax.

1. If possible (I didn't check it), configure Sequel Pro to use `mysqldump` instead of the very own implementation.

1. Run manually `mysqldump` on the server (maybe even Sequel Pro supports some console or provides directly an interfaces for running `mysqldump`).

1. Use a different tool than Sequel Pro for accessing the MySQL database.

1. Use another instance of MySQL (e.g. on your own PC or notebook), load the by-Sequel-Pro-exported SQL file and then finally run `mysqldump` manually on this DB.

1. Modify the `mysql2sqlite` script to parse even the Sequel Pro SQL export file (and if the changes won't much influence the current parsing, issue a [pull request](https://help.github.com/articles/about-pull-requests/ ) and I might merge it.

**Comment by mdinh186** [comment]
Thank you for looking into the issues! I followed your suggestion to create dump file from MySQL instance and run the script again. This time all works perfectly!

**Comment by DarrenGDC** [comment]
@mdinh186  you'd better close the issue, if your problem has been fixed.

**Comment by dumblob** [comment]
You're welcome.
